version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.29
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.38
    - 14.14.41
    - 15.0.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
    - 4.2.16
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.11
  - dependency-name: chai
    versions:
    - 4.3.3
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: gulp-mocha
    versions:
    - 7.0.2
